version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.local
    image: local/scaffold
    container_name: scaffold_web
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
      WEBPACKER_DEV_SERVER_PUBLIC: 0.0.0.0:3035
    entrypoint: docker/entrypoint.sh
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
      - "3035:3035"
    tty: true
    stdin_open: true
    depends_on:
      - db

  db:
    image: postgres:11.1-alpine
    container_name: scaffold_db
    environment:
      TZ: Asia/Tokyo
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./docker/postgres/volume:/var/lib/postgresql/data
